# **1주차 복습과제**
- 1주차 복습과제는 **넘파이/판다스 연습문제**입니다.
- 코드 작성하시고, 출력 결과까지 나오도록 실행 부탁드립니다.
  - 제출 시 파일명 본인 이름으로 변경해 주세요. ex) Week1_복습과제_OOO
- 교재에서 다루지 않은 메소드도 다수 포함되어 있지만 구글링이나 챗지피티 등을 활용해서라도 풀어주세요! 한 번씩 사용해 보면 좋을 것 같아 어려워도 문제에 포함했습니다 🤗

## **넘파이**

### 1. Import the numpy package under the name `np`.

In [ ]:
import numpy as np

### 2. Print the numpy version and the configuration.

(hint: `np.__version__`, `np.show_config`)

In [ ]:
print("NumPy version:", np.__version__)

np.show_config()

NumPy version: 1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep140213194937296
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    args: -fno-strict-aliasing
    commands: cc
    linker: ld.bfd
    linker args: -Wl,--strip-debug, -fno-strict-aliasing
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    linker args: -Wl,--strip-debug
    name: gcc
    version: 10.2.1
  cython:
    commands: cython
    linker: cython
    n

### 3. Create a null vector of size 10.

#### ✅ 출력 예시


```
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
```



In [ ]:
null_vector = np.zeros(10)

print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


### 4. Create a null vector of size 10 but the fifth value which is 1.

#### ✅출력 예시


```
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
```

In [ ]:
null_vector = np.zeros(10)
null_vector[4] = 1

print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


### 5. Create a vector with values ranging from 10 to 49.

#### ✅출력 예시


```
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
```

In [ ]:
vector = np.arange(start = 10, stop = 50)

print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


### 6. Reverse a vector (first element becomes last).

#### ✅출력 예시


```
[9 8 7 6 5 4 3 2 1 0]
```

In [ ]:
org_array = np.arange(10)
sort_array = np.sort(org_array)[::-1]

print(sort_array)

[9 8 7 6 5 4 3 2 1 0]


### 7. Create a 3x3 matrix with values ranging from 0 to 8.

#### ✅출력 예시


```
[[0 1 2]
 [3 4 5]
 [6 7 8]]
```

In [ ]:
array1 = np.arange(9)
array2 = array1.reshape(3, 3)

print(array2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### 8. Find indices of non-zero elements from [1,2,0,0,4,0].

#### ✅출력 예시


```
(array([0, 1, 4]),)
```

In [ ]:
array1 = np.array([1, 2, 0, 0, 4, 0])
non_zero_indices = np.nonzero(array1)

print(non_zero_indices)

(array([0, 1, 4]),)


### 9. Create a 3x3 identity matrix.

(hint: `np.eye`)

#### ✅출력 예시


```
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
```

In [ ]:
matrix = np.eye(3)

print(matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### 10. Create a 3x3x3 array with random values.

#### ✅출력 예시


```
[[[0.30742852 0.26458726 0.85474383]
  [0.80234531 0.76268902 0.91286677]
  [0.8804109  0.51011378 0.82103555]]

 [[0.403753   0.83120234 0.15202655]
  [0.75782685 0.0732058  0.48148689]
  [0.2089428  0.44968622 0.88134184]]

 [[0.52251191 0.10738374 0.86279648]
  [0.26203911 0.42157754 0.68856833]
  [0.58133626 0.31059127 0.71354172]]]
```

In [ ]:
random_matrix = np.random.rand(3,3,3)

print(random_matrix)

[[[0.7562099  0.93005301 0.74771781]
  [0.94526661 0.54122498 0.22669846]
  [0.59413557 0.46469691 0.43665847]]

 [[0.94836866 0.12558177 0.65345985]
  [0.8498641  0.32736279 0.9345845 ]
  [0.05382236 0.56262217 0.82065483]]

 [[0.04288223 0.548721   0.35242416]
  [0.68651878 0.69357105 0.24772381]
  [0.034144   0.67733392 0.18576669]]]


### 11. Create a 10x10 array with random values and find the minimum and maximum values.

#### ✅출력 예시


```
0.018360924693465508 0.9990506368595156
```

In [ ]:
random_matrix = np.random.rand(10,10)
min_value = np.min(random_matrix)
max_value = np.max(random_matrix)

print(min_value, max_value)

0.01650838572388169 0.9974719810320255


### 12. Create a random vector of size 30 and find the mean value.

#### ✅출력 예시


```
0.46249036320403636
```

In [ ]:
random_vector = np.random.rand(30)
mean_value = np.mean(random_vector)

print(mean_value)

0.5600528667246973


### 13. Create a 2d array with 1 on the border and 0 inside. (size: 10x10)

#### ✅출력 예시


```
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
```

In [ ]:
array = np.zeros((10, 10))

array[0, :] = 1
array[-1, :] = 1
array[:, 0] = 1
array[:, -1] = 1

print(array)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


### 14. How to add a border (filled with 0's) around an existing array?

(hint: 인덱싱 사용)

#### ✅출력 예시


```
# before
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

 # after
 [[0. 0. 0. 0. 0.]
  [0. 1. 1. 1. 0.]
  [0. 1. 1. 1. 0.]
  [0. 1. 1. 1. 0.]
  [0. 0. 0. 0. 0.]]

```

In [ ]:
print('# before')
array = np.ones((5,5))
print(array)
print('\n')

print('# after')
array[0, :] = [0]
array[-1, :] = [0]
array[:, 0] = [0]
array[:, -1] = [0]
print(array)

# before
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


# after
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


### 15. What is the result of the following expression?

(실행 후, 결과에 대한 주석 작성해주세요. ex. 출력 결과에 대한 이유)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
0 * np.nan # Nan은 "Not a Number(숫자가 아님)"을 뜻하므로, 정의되지 않는다. 그러므로 'Nan * 0' 값도 정의되지 않으므로 결과는 'Nan'이 나온다.

nan

In [ ]:
np.nan == np.nan # Nan은 "Not a Number(숫자가 아님)"을 뜻하므로, 정의되지 않는다. 그러므로 자기 자신(Nan)과도 비교할 수 없기 때문에 False가 나온다.

False

In [ ]:
np.inf > np.nan # Nan은 "Not a Number(숫자가 아님)"을 뜻하므로, 정의되지 않는다. 그러므로 자기 자신(Nan)과도 비교할 수 없기 때문에 False가 나온다.

False

In [ ]:
np.nan - np.nan # Nan은 "Not a Number(숫자가 아님)"을 뜻하므로, 정의되지 않는다. 따라서 Nan - Nan 의 결과도 의미를 정의할 수 없어서 nan이 나온다.

nan

In [ ]:
np.nan in set([np.nan]) # set은 해시 값 기반으로 동작하기 때문에 in 연산자는 True가 됨.

True

In [ ]:
0.3 == 3 * 0.1 # 3 * 0.1의 실제 값은 **0.3이 아니라 0.30000000000000004**로 저장된다. 따라서, False가 반환된다.

False

### 16. Normalize a 5x5 random matrix.

(hint: (x - mean) / std)

#### ✅출력 예시


```
[[-1.4765971   0.9582795  -1.29910242  1.0250981  -0.79801651]
 [ 0.57945383 -1.28559078  0.02733238  0.99675052  1.2702088 ]
 [-0.08513084 -1.4686812  -0.78813593 -0.34559303 -1.15052328]
 [ 0.98183813 -1.41255344  0.37190169  1.05697419 -0.02668639]
 [-1.14466851  0.98911205  1.14499256  0.69454882  1.18478886]]
```

In [ ]:
matrix = np.random.rand(5, 5)
mean = np.mean(matrix)
std = np.std(matrix)
normalized_matrix = (matrix - mean) / std

print(normalized_matrix)

[[ 1.29449895  1.0303931  -1.11044386 -1.68789173  1.12548163]
 [ 0.09517922 -1.51844905 -0.27070859 -0.50830066 -0.76910344]
 [-0.43794901 -0.22567766  1.2896404  -1.02327423  1.10081433]
 [ 0.98923717  1.49343322  1.15796064 -1.34934121 -0.89056336]
 [ 1.03410886 -0.00325664  0.56201614 -0.60818971 -0.76961452]]


### 17. Multiply a 5x3 matrix by a 3x2 matrix. (real matrix product)

#### ✅출력 예시


```
[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]
```

In [ ]:
matrix1 = np.ones((5,3))
matrix2 = np.ones((3,2))
result = np.dot(matrix1, matrix2)

print(result)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


### 18. What are the result of the following expressions?

(실행 후, 결과에 대한 주석 작성해주세요. ex. 출력 결과에 대한 이유)

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
np.array(0) / np.array(0) # 명확한 값이 존재하지 않기 때문에 nan이 나온다.

<ipython-input-23-12c8f54f9b6e>:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0) # 명확한 값이 존재하지 않기 때문에 nan이 나온다.


nan

In [ ]:
np.array(0) // np.array(0) # C 언어 기반의 NumPy의 내부 처리 방식 때문에, 정수형 나눗셈(//) 연산에서는 0 // 0의 값이 0으로 나온다.

<ipython-input-24-29c65adae845>:1: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0) # C 언어 기반의 NumPy의 내부 처리 방식 때문에, 정수형 나눗셈(//) 연산에서는 0 // 0의 값이 0으로 나온다.


0

In [ ]:
np.array([np.nan]).astype(int).astype (float)
# np.nan은 정수로 변환할 수 없는 값이므로, Numpy는 이를 최소 정수값으로 변환한다. 그리고 이 값을 float 형식으로 변환하는 것이다.

<ipython-input-25-3cbcfe508a4e>:1: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype (float)


array([-9.22337204e+18])

### 19. Create a 5x5 matrix with row values ranging from 0 to 4.

#### ✅ 출력 예시

```
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
```

In [ ]:
matrix = np.tile(np.arange(5), (5, 1))
# np.arange(5)를 5번 반복하여 row 생성, 1번 반복하여 column 생성

print(matrix)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


### 20. Create a random vector of size 10 and sort it.

#### ✅출력 예시


```
[0.11443045 0.16715169 0.32515597 0.38374227 0.48327044 0.78728921
 0.80523192 0.85915686 0.96930939 0.99586525]

```

In [ ]:
random_matrix = np.random.rand(10)
random_sort = random_matrix.sort()

print(random_matrix)

[0.20397898 0.3307539  0.39767325 0.44076418 0.49456719 0.58133514
 0.60235864 0.85047393 0.94154538 0.9436053 ]


## **판다스**


### 1. Import pandas under the alias `pd`.

In [ ]:
import pandas as pd

### 2. Print the version of pandas that has been imported.

In [ ]:
print(pd.__version__)

2.2.2


## 3~20번 문제는 아래 데이터프레임으로 진행됩니다.

Consider the following Python dictionary `data` and Python list `labels`:

``` python
data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```


### 3. Create a DataFrame `df` from this dictionary `data` which has the index `labels`.


In [ ]:
# 문제 풀이 전 numpy 임포트
import numpy as np

data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(data, index=labels)

print(df)

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  2.0       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no


### 4. Display a summary of the basic information about this DataFrame and its data.  
(hint: there is a single method that can be called on the DataFrame)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, a to j
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   animal    10 non-null     object 
 1   age       8 non-null      float64
 2   visits    10 non-null     int64  
 3   priority  10 non-null     object 
dtypes: float64(1), int64(1), object(2)
memory usage: 400.0+ bytes


### 5. Display a summary of the basic statistics about data of this DataFrame.  
(hint: there is a single method that can be called on the DataFrame)

In [ ]:
df.describe()

age     visits
count  8.000000  10.000000
mean   3.437500   1.900000
std    2.007797   0.875595
min    0.500000   1.000000
25%    2.375000   1.000000
50%    3.000000   2.000000
75%    4.625000   2.750000
max    7.000000   3.000000

### 6. Return the first 3 rows of the DataFrame `df`.

In [ ]:
df.head(3)

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no

### 7. Select just the 'animal' and 'age' columns from the DataFrame `df`.

In [ ]:
select_column = df[['animal','age']]

print(select_column)

  animal  age
a    cat  2.5
b    cat  3.0
c  snake  0.5
d    dog  NaN
e    dog  5.0
f    cat  2.0
g  snake  4.5
h    cat  NaN
i    dog  7.0
j    dog  3.0


### 8. Select the data in rows `[3, 4, 8]` **and** in columns `['animal', 'age']`.

In [ ]:
select_data2 = df.iloc[[3,4,8],[0,1]]

print(select_data2)


  animal  age
d    dog  NaN
e    dog  5.0
i    dog  7.0


### 9. Select only the rows where the number of visits is greater than 3.

In [ ]:
df[df['visits'] > 3]
# visits 값이 3보다 큰 값이 없으므로 빈 DataFrame이 출력됨.

Empty DataFrame
Columns: [animal, age, visits, priority]
Index: []

### 10. Select the rows where the age is missing, i.e. it is `NaN`.

In [ ]:
age_missing = df[df['age'].isna()]

print(age_missing)

  animal  age  visits priority
d    dog  NaN       3      yes
h    cat  NaN       1      yes


### 11. Select the rows where the animal is a cat *and* the age is less than 3.

In [ ]:
row1 = df[(df['animal'] == 'cat') & (df['age'] < 3)]

print(row1)

  animal  age  visits priority
a    cat  2.5       1      yes
f    cat  2.0       3       no


### 12. Select the rows the age is between 2 and 4 (inclusive).  


In [ ]:
row2 = df[(df['age'] <= 4) & (df['age'] >= 2)]

print(row2)

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
f    cat  2.0       3       no
j    dog  3.0       1       no


### 13. Change the age in row 'f' to 1.5.

In [ ]:
df.loc['f', 'age'] = 1.5

print(df)

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  1.5       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no


### 14. Calculate the sum of all visits in `df` (i.e. the total number of visits).

In [ ]:
sum_visits = df['visits'].sum()

print(sum_visits)

19


### 15. Calculate the mean age for each different animal in `df`.

In [ ]:
mean_age = df.groupby('animal')['age'].mean()

print(mean_age)

animal
cat      2.333333
dog      5.000000
snake    2.500000
Name: age, dtype: float64


### 16. Append a new row 'k' to `df` with your choice of values for each column. Then delete that row to return the original DataFrame.

In [ ]:
df.loc['k'] = ['monkey', 2.9, 4, 'yes']
print(df)

print('\n')

df = df.drop('k')
print(df)

   animal  age  visits priority
a     cat  2.5       1      yes
b     cat  3.0       3      yes
c   snake  0.5       2       no
d     dog  NaN       3      yes
e     dog  5.0       2       no
f     cat  1.5       3       no
g   snake  4.5       1       no
h     cat  NaN       1      yes
i     dog  7.0       2       no
j     dog  3.0       1       no
k  monkey  2.9       4      yes


  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  1.5       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no


### 17. Count the number of each type of animal in `df`.

In [ ]:
count_animal = df['animal'].value_counts()
print(count_animal)

animal
cat      4
dog      4
snake    2
Name: count, dtype: int64


### 18. Sort `df` first by the values in the 'age' in *decending* order, then by the value in the 'visits' column in *ascending* order (so row `i` should be first, and row `d` should be last).
#### ✅출력 예시

index |animal	| age	|visits|	priority
---|---|---|---|---
i|	dog|	7.0|	2|	no
e|	dog|	5.0|	2|	no
g|	snake|	4.5|	1|	no
j|	dog|	3.0|	1|	no
b|	cat|	3.0|	3|	yes
a|	cat|	2.5|	1|	yes
f|	cat|	1.5|	3|	no
c|	snake|	0.5|	2|	no
h|	cat|	NaN|	1|	yes
d|	dog|	NaN|	3|	yes

In [ ]:
df_sorted = df.sort_values(by = ['age', 'visits'], ascending = [False, True])

print(df_sorted)

  animal  age  visits priority
i    dog  7.0       2       no
e    dog  5.0       2       no
g  snake  4.5       1       no
j    dog  3.0       1       no
b    cat  3.0       3      yes
a    cat  2.5       1      yes
f    cat  1.5       3       no
c  snake  0.5       2       no
h    cat  NaN       1      yes
d    dog  NaN       3      yes


### 19. The 'priority' column contains the values 'yes' and 'no'. Replace this column with a column of boolean values: 'yes' should be `True` and 'no' should be `False`.  
(hint: `map`)

In [ ]:
map_priority = {'yes' : 'True', 'no' : 'False'}
df['priority'] = df['priority'].map(map_priority)

print(df)

  animal  age  visits priority
a    cat  2.5       1     True
b    cat  3.0       3     True
c  snake  0.5       2    False
d    dog  NaN       3     True
e    dog  5.0       2    False
f    cat  1.5       3    False
g  snake  4.5       1    False
h    cat  NaN       1     True
i    dog  7.0       2    False
j    dog  3.0       1    False


### 20. In the 'animal' column, change the 'snake' entries to 'python'.   

In [ ]:
df = pd.DataFrame({'animal' : ['cat', 'dog', 'snake', 'dog', 'cat', 'snake']})
df['animal'] = df['animal'].replace('snake', 'python')

In [ ]:
# 확인용 df 출력 셀
df

animal
0     cat
1     dog
2  python
3     dog
4     cat
5  python

### 21. Given a DataFrame of random numeric values:
```python
df = pd.DataFrame(np.random.random(size=(5, 3))) # this is a 5x3 DataFrame of float values
```

how do you subtract the row mean from each element in the row?

In [ ]:
# 랜덤 시드 고정
np.random.seed(2025)

df = pd.DataFrame(np.random.random(size=(5, 3)))




In [ ]:
df_subtract = df.sub(df.mean(axis = 1), axis = 0)
print(df_subtract)

          0         1         2
0 -0.516494  0.235870  0.280624
1  0.081768  0.024435 -0.106204
2 -0.047373 -0.212124  0.259497
3  0.115235 -0.230544  0.115309
4 -0.229731  0.498009 -0.268278
